version: 2

project_name: eaRS

builds:
  - id: ears
    binary: ears
    main: ./fake-main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    hooks:
      pre:
        - sh -c "case '{{.Os}}_{{.Arch}}' in
          linux_amd64) cargo build --release --target x86_64-unknown-linux-gnu && cp target/x86_64-unknown-linux-gnu/release/ears {{ .Path }} ;;
          linux_arm64) cargo build --release --target aarch64-unknown-linux-gnu && cp target/aarch64-unknown-linux-gnu/release/ears {{ .Path }} ;;
          darwin_amd64) cargo build --release --target x86_64-apple-darwin && cp target/x86_64-apple-darwin/release/ears {{ .Path }} ;;
          darwin_arm64) cargo build --release --target aarch64-apple-darwin && cp target/aarch64-apple-darwin/release/ears {{ .Path }} ;;
          windows_amd64) cargo build --release --target x86_64-pc-windows-gnu && cp target/x86_64-pc-windows-gnu/release/ears.exe {{ .Path }} ;;
          esac"

before:
  hooks:
    - rustup target add x86_64-unknown-linux-gnu
    - rustup target add x86_64-pc-windows-gnu
    - rustup target add x86_64-apple-darwin
    - rustup target add aarch64-apple-darwin
    - rustup target add aarch64-unknown-linux-gnu
    - echo "package main\nfunc main() {}" > fake-main.go

archives:
  - id: ears
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - config/*.toml

nfpms:
  - id: ears
    package_name: ears
    vendor: byteowlz
    homepage: https://byteowlz.com
    maintainer: Tommy Falkowski <email@example.com>
    description: Easy automatic speech recognition library using Kyutai's STT models
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: config/config.toml
        dst: /etc/ears/config.toml
        type: config

brews:
  - name: ears
    repository:
      owner: byteowlz
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    url_template: "https://github.com/tommyfalkowski/eaRS/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: https://byteowlz.com
    description: Easy automatic speech recognition library using Kyutai's STT models
    license: MIT
    install: |
      bin.install "ears"
      etc.install "config/config.toml" => "ears/config.toml"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: tommyfalkowski
    name: eaRS
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"